---
services:
  postgres:
    # https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/
    image: postgres:latest
    container_name: postgres
    # we won't expose ports
    # containers will communicate via internal docker network
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql
      - backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  django:
    build:
      context: webserver/
      dockerfile: ./compose/local/django/Dockerfile
    image: django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

networks:
  backend:
    name: backend
    driver: bridge  # isolated from host network

volumes:
  postgres_data:
    name: postgres
  backups:
    name: backups
